#server
server:
  port: 7060
  tomcat:
    accept-count: 10
    threads:
      max: 10
      min-spare: 5
  error:
    path: /liyz/error
  shutdown: graceful
# spring
spring:
  application:
    name: cloud-api-monitor
    admin:
      enabled: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 60s
  cloud:
    nacos:
      discovery:
        server-addr: nacos://localhost:8848
        namespace: liyz-cloud
# log
logging:
  file:
    name: '\srv\logs\${spring.application.name}\${spring.application.name}.log'
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
# management
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: when_authorized
