server:
  port: 9095
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: service-gateway
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
#gateway-#路由规则
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
          - id: header_route
            uri: http://localhost:8093
            predicates:
            - Header=Authorization, .*?

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8096/eureka/
  instance:
    health-check-url-path: /actuator/health
#一下配置，在生产环境注意，选择性配置
management:
  endpoint:
    web:
      exposure:
        include: '*'
    health:
      show-details: always


