app:
  id: cloud-service-gateway
apollo:
  meta: http://127.0.0.1:8080
  cluster: default
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application
#gateway-#路由规则
spring:
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
          - id: header_route
            uri: http://localhost:8053
            predicates:
            - Header=Authorization, .*?